# -*- coding: utf-8 -*-
"""lazypredict_projections.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HGektCha7Sqs1vWWANRJF6KUUzUlZ3mt
"""

import lightgbm
import sklearn.svm
import scipy.stats
from sklearn.model_selection import train_test_split
from lazypredict.Supervised import LazyRegressor
import torch
import numpy as np


def pearsonr(x, y):
    a, b = scipy.stats.pearsonr(x, y)
    return b


def fit_regressor_calculate_correlation(regressor, corr_function, x_train, x_test, y_train, y_test):
    regressor.fit(x_train, y_train)
    y_pred = regressor.predict(x_test)
    return corr_function(y_pred, y_test)


X = torch.load('X_tensor_cpu.pt')
y = torch.load('y_tensor.pt')

for i in range(len(X)):
    for j in range(len(X[i])):
        X[i][j] = X[i][j].detach().numpy()

X = np.array(X)
y = np.array(y)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.5, random_state=123)

reg = LazyRegressor()
models, predictions = reg.fit(X_train, X_test, y_train, y_test)

print(models)

REGRESSORS = [
    sklearn.tree._classes.ExtraTreeRegressor,
    sklearn.svm.SVR,
    lightgbm.LGBMRegressor,
    sklearn.svm._classes.NuSVR,
    sklearn.ensemble._hist_gradient_boosting.gradient_boosting.HistGradientBoostingRegressor,
]

PEARSON_CORRELATIONS = []

for regressor in REGRESSORS:
    PEARSON_CORRELATIONS.append((regressor.__name__, fit_regressor_calculate_correlation(
        regressor(), scipy.stats.pearsonr, X_train, X_test, y_train, y_test)[0]))

print(sorted(PEARSON_CORRELATIONS, key=lambda x: -x[1]))

SPEARMAN_CORRELATIONS = []

for regressor in REGRESSORS:
    SPEARMAN_CORRELATIONS.append((regressor.__name__, fit_regressor_calculate_correlation(
        regressor(), scipy.stats.spearmanr, X_train, X_test, y_train, y_test)))

print(sorted(SPEARMAN_CORRELATIONS, key=lambda x: -x[0]))
